"""
mcp_servers/social_server.py

Handles YouTube video uploads using the YouTube Data API v3.

Project selection:
  - Even-indexed videos → project A
  - Odd-indexed videos  → project B  (falls back to A if B creds not set)

FIX: Added thumbnail upload support via youtube.thumbnails().set() after
video upload. Previously thumbnails were generated by _generate_thumbnail()
in video_workflow.py but never attached to the YouTube video — the API
requires a separate thumbnails.set() call with a MediaFileUpload.
"""
import os
import time
from loguru import logger

try:
    from googleapiclient.discovery import build
    from googleapiclient.http import MediaFileUpload
    from google.oauth2.credentials import Credentials
    GOOGLE_LIBS = True
except ImportError:
    GOOGLE_LIBS = False


class SocialMCPServer:
    def __init__(self):
        self.tools = {
            "upload_youtube": self._upload_youtube,
        }

    def call(self, tool_name: str, **kwargs):
        if tool_name not in self.tools:
            return {"success": False, "error": f"Unknown tool: {tool_name}"}
        return self.tools[tool_name](**kwargs)

    def _has_credentials(self, project: str) -> bool:
        return all([
            os.environ.get(f"YOUTUBE_CLIENT_ID_{project}"),
            os.environ.get(f"YOUTUBE_CLIENT_SECRET_{project}"),
            os.environ.get(f"YOUTUBE_REFRESH_TOKEN_{project}"),
        ])

    def _get_youtube_client(self, project: str = "A"):
        if not GOOGLE_LIBS:
            raise RuntimeError("google-api-python-client not installed")

        if not self._has_credentials(project):
            if project != "A" and self._has_credentials("A"):
                logger.warning(
                    f"YouTube project {project} credentials not set — "
                    f"falling back to project A"
                )
                project = "A"
            else:
                raise ValueError(
                    f"Missing YouTube credentials for project {project}. "
                    f"Set YOUTUBE_CLIENT_ID_{project}, YOUTUBE_CLIENT_SECRET_{project}, "
                    f"and YOUTUBE_REFRESH_TOKEN_{project} in GitHub Secrets."
                )

        creds = Credentials(
            token=None,
            refresh_token=os.environ[f"YOUTUBE_REFRESH_TOKEN_{project}"],
            client_id=os.environ[f"YOUTUBE_CLIENT_ID_{project}"],
            client_secret=os.environ[f"YOUTUBE_CLIENT_SECRET_{project}"],
            token_uri="https://oauth2.googleapis.com/token",
        )
        return build("youtube", "v3", credentials=creds)

    def _upload_youtube(
        self,
        video_path: str,
        title: str,
        description: str,
        tags: list,
        category_id: str = "22",
        privacy: str = "public",
        made_for_kids: bool = False,
        project: str = "A",
        thumbnail_path: str = None,   # FIX: new parameter
        **kwargs,
    ):
        if not os.path.exists(video_path):
            return {"success": False, "error": f"Video file not found: {video_path}"}

        if not GOOGLE_LIBS:
            logger.warning("Google API libraries not installed. Simulating upload.")
            simulated_id = f"SIMULATED_{int(time.time())}"
            return {
                "success": True,
                "youtube_url": f"https://youtube.com/shorts/{simulated_id}",
                "video_id": simulated_id,
                "simulated": True,
                "thumbnail_uploaded": False,
            }

        try:
            youtube = self._get_youtube_client(project)

            body = {
                "snippet": {
                    "title": title[:100],
                    "description": description[:5000],
                    "tags": tags[:500],
                    "categoryId": category_id,
                },
                "status": {
                    "privacyStatus": privacy,
                    "selfDeclaredMadeForKids": made_for_kids,
                },
            }

            media = MediaFileUpload(
                video_path, chunksize=1024 * 1024, resumable=True, mimetype="video/mp4"
            )
            request = youtube.videos().insert(
                part=",".join(body.keys()), body=body, media_body=media
            )

            response = None
            while response is None:
                status, response = request.next_chunk()
                if status:
                    logger.info(f"Upload progress: {int(status.progress() * 100)}%")

            video_id = response.get("id", "")
            youtube_url = f"https://youtube.com/shorts/{video_id}"
            logger.success(f"Uploaded to YouTube: {youtube_url}")

            # FIX: Upload thumbnail via thumbnails().set() after video upload.
            # Previously the thumbnail file was generated but never sent to YouTube
            # because the videos.insert() body does not accept a thumbnail —
            # it requires a separate thumbnails.set() API call.
            thumbnail_uploaded = False
            if thumbnail_path and video_id:
                thumbnail_uploaded = self._upload_thumbnail(youtube, video_id, thumbnail_path)

            return {
                "success": True,
                "youtube_url": youtube_url,
                "video_id": video_id,
                "thumbnail_uploaded": thumbnail_uploaded,
            }

        except Exception as e:
            logger.error(f"YouTube upload failed: {e}")
            return {"success": False, "error": str(e)}

    def _upload_thumbnail(self, youtube, video_id: str, thumbnail_path: str) -> bool:
        """
        FIX: Upload a custom thumbnail to a YouTube video.

        Requires the channel to have custom thumbnail access enabled.
        YouTube requires thumbnails to be:
          - JPEG, PNG, GIF, or BMP format
          - Under 2 MB
          - 1280x720 px recommended (16:9 ratio)

        This is a non-fatal operation — if it fails, the video still
        goes live with YouTube's auto-generated thumbnail.
        """
        if not os.path.exists(thumbnail_path):
            logger.warning(f"Thumbnail file not found, skipping: {thumbnail_path}")
            return False

        file_size = os.path.getsize(thumbnail_path)
        if file_size < 10_000:
            logger.warning(
                f"Thumbnail too small ({file_size} bytes) — likely a failed "
                f"Pollinations response. Skipping thumbnail upload."
            )
            return False

        if file_size > 2 * 1024 * 1024:
            logger.warning(
                f"Thumbnail too large ({file_size / 1024 / 1024:.1f} MB, max 2 MB). "
                f"Skipping thumbnail upload."
            )
            return False

        try:
            # Determine MIME type from extension
            ext = os.path.splitext(thumbnail_path)[1].lower()
            mime_map = {
                ".jpg": "image/jpeg",
                ".jpeg": "image/jpeg",
                ".png": "image/png",
                ".gif": "image/gif",
                ".bmp": "image/bmp",
                ".webp": "image/webp",
            }
            mime_type = mime_map.get(ext, "image/jpeg")

            thumb_media = MediaFileUpload(
                thumbnail_path,
                mimetype=mime_type,
                resumable=False,
            )

            youtube.thumbnails().set(
                videoId=video_id,
                media_body=thumb_media,
            ).execute()

            logger.success(
                f"Thumbnail uploaded for video {video_id} "
                f"({file_size // 1024} KB, {mime_type})"
            )
            return True

        except Exception as e:
            # Thumbnail upload failure is non-fatal — video is already live
            logger.warning(
                f"Thumbnail upload failed for video {video_id} (non-fatal): {e}"
            )
            return False
