"""
agents/visual_director.py

UPGRADED v2: Rapid visual cutting + script-driven scene queries.

Key changes from v1:
  1. RAPID CUTTING: num_scenes now targets duration // 3 instead of duration // 8.
     For a 55s video this means ~18 scenes (was ~6). Each scene = one visual cut.
     This matches the cut rate of top viral Shorts (one cut every 2-4 seconds).

  2. SCENE-TO-SENTENCE MATCHING: Scene prompts are generated by splitting the
     script's sentences and using each sentence as a visual query. This ensures
     the visual directly illustrates what is being said at that moment.

  3. VISUAL ANCHOR INTEGRATION: The Pass 1 extractor's visual_anchors field
     (new in script_writer.py v2) is used to generate the most impactful scenes.

  4. Existing strategy (AI images for horror/motivation/brainrot, stock video
     for reddit_story/finance) is preserved — just with more scenes.
"""
import os
import re
import random
import requests
from pathlib import Path
from loguru import logger
from mcp_servers.image_server import ImageMCPServer
from mcp_servers.video_fetcher import VideoFetcherMCPServer


# ---------------------------------------------------------------------------
# Niches that benefit from AI-generated images vs realistic stock footage
# ---------------------------------------------------------------------------
AI_IMAGE_NICHES    = {"horror", "motivation", "brainrot"}
STOCK_VIDEO_NICHES = {"reddit_story", "finance"}

# ---------------------------------------------------------------------------
# Emotion → Ken Burns motion preset
# ---------------------------------------------------------------------------
EMOTION_KB_PRESET = {
    "fear":        "slow_zoom_in",
    "inspiration": "zoom_out",
    "urgency":     "zoom_out",
    "chaos":       "fast_pan",
    "amusement":   "fast_pan",
    "curiosity":   "slow_zoom_in",
    "shock":       "slow_zoom_in",
    "default":     "slow_zoom_in",
}

# ---------------------------------------------------------------------------
# Niche visual style suffixes appended to AI image prompts
# ---------------------------------------------------------------------------
NICHE_IMAGE_STYLE = {
    "motivation":   "cinematic, golden hour, dramatic lighting, photorealistic, 4K, vertical",
    "horror":       "dark, moody, hyper-realistic, atmospheric fog, horror film still, vertical",
    "reddit_story": "candid, realistic, everyday life, natural lighting, vertical photo",
    "brainrot":     "neon colors, chaotic, surreal, internet aesthetic, vertical",
    "finance":      "clean, professional, minimalist, corporate, sharp lighting, vertical",
}

# ---------------------------------------------------------------------------
# Fallback generic queries when extractor data is unavailable
# ---------------------------------------------------------------------------
NICHE_FALLBACK_QUERIES = {
    "motivation": [
        "person standing on mountain summit at sunrise",
        "runner crossing finish line dramatic lighting",
        "lone figure walking through fog determination",
        "hands reaching toward sky golden hour",
        "person breaking through wall of obstacles",
        "athlete training at dawn empty stadium",
        "winner holding trophy dramatic sky",
        "person meditating sunrise cliff edge",
        "team celebrating achievement office",
        "close up eyes determined focus",
    ],
    "horror": [
        "dark empty hallway house at night",
        "shadows on wall abandoned building",
        "door slightly open darkness beyond",
        "fog covered road trees at midnight",
        "silhouette in window dark house",
        "basement stairs leading to darkness",
        "old phone ringing in dark room",
        "face reflected in dark window",
        "abandoned hospital corridor flickering light",
        "child's toy in empty dark room",
    ],
    "reddit_story": [
        "person typing on phone coffee shop",
        "two people arguing apartment",
        "shocked face looking at phone screen",
        "person walking away city street",
        "hands shaking while holding phone",
        "couple in tense conversation kitchen",
        "person reading message shocked",
        "office confrontation between coworkers",
        "door slamming in apartment building",
        "person crying in parked car",
    ],
    "brainrot": [
        "neon lights abstract chaos colorful",
        "person screaming funny surreal",
        "internet meme energy chaotic background",
        "brain explosion colorful abstract",
        "glitch art digital chaos neon",
        "spinning 3d objects colorful",
        "meme face surprised expression",
        "colorful explosion abstract art",
        "cat looking confused neon background",
        "cursed image energy surreal art",
    ],
    "finance": [
        "stock market graph going up dramatic",
        "wallet with money close up",
        "person looking at laptop financial data",
        "city skyscrapers business district",
        "coins and bills arranged neatly",
        "calculator and financial documents",
        "piggy bank savings concept",
        "hands counting money close up",
        "stock exchange trading floor",
        "person signing financial document",
    ],
}


class VisualDirectorAgent:
    def __init__(self, config):
        self.config        = config
        self.image_server  = ImageMCPServer()
        self.video_fetcher = VideoFetcherMCPServer()
        self.image_config  = config.get("images", {})
        self.video_config  = config.get("video", {})

    def _get_niche(self) -> str:
        return os.environ.get(
            "NICHE",
            self.config.get("video", {}).get("niche", "motivation")
        )

    # ------------------------------------------------------------------
    # UPGRADED: Build scene prompts from script sentences + extractor data
    # ------------------------------------------------------------------
    def _build_scene_prompts(self, script: dict, niche: str, num_scenes: int) -> list:
        """
        Generate distinct visual prompts for each rapid-cut scene.

        Priority order:
        1. Script sentences (each sentence = one visual cut)
        2. visual_anchors from Pass 1 extractor
        3. key_facts from Pass 1 extractor
        4. Niche fallback queries
        """
        style_suffix = NICHE_IMAGE_STYLE.get(niche, "cinematic, photorealistic, vertical")
        topic_brief  = script.get("topic_brief", {})
        emotion      = script.get("emotion", "curiosity")
        extracted    = script.get("_extracted", {})

        title   = script.get("title", "")
        topic   = topic_brief.get("topic", title)

        prompts = []

        # ── Method 1: Extract visual prompts FROM script sentences ───────────
        # Each sentence in the script should map to one visual scene
        script_text = script.get("script", "")
        if script_text:
            sentences = [s.strip() for s in script_text.split(".") if s.strip() and len(s.strip()) > 5]
            for sentence in sentences[:num_scenes]:
                # Remove non-visual filler words
                clean = re.sub(
                    r'\b(you|your|the|a|an|and|or|but|in|on|at|to|for|of|with|by|'
                    r'this|that|is|was|are|were|has|have|had|they|we|it|be|been|'
                    r'will|would|could|should|do|did|not|no|so|if|then|'
                    r'now|here|there|just|still|even|most|many|some|all|more)\b',
                    '',
                    sentence.lower()
                ).strip()
                clean = re.sub(r'\s+', ' ', clean)[:70]
                if len(clean.split()) >= 2:
                    prompts.append(f"{clean}, {style_suffix}")

        # ── Method 2: Visual anchors from extractor ──────────────────────────
        visual_anchors = extracted.get("visual_anchors", [])
        for anchor in visual_anchors:
            if anchor and len(anchor) > 5:
                anchor_clean = re.sub(r'[^\w\s]', '', anchor)[:70]
                prompts.append(f"{anchor_clean}, {style_suffix}")

        # ── Method 3: Key facts from extractor ───────────────────────────────
        key_facts = extracted.get("key_facts", [])
        for fact in key_facts[:3]:
            if fact and len(fact) > 5:
                fact_clean = re.sub(r'[^\w\s]', '', fact)[:70]
                prompts.append(f"{fact_clean}, {style_suffix}")

        # ── Method 4: Hook and twist ──────────────────────────────────────────
        hook = script.get("hook", "")
        if hook:
            hook_clean = re.sub(
                r'\b(i|you|we|they|the|a|an)\b', '', hook.lower()
            ).strip()[:60]
            prompts.insert(0, f"{hook_clean}, {style_suffix}")  # Hook = first visual

        twist = extracted.get("twist", "")
        if twist:
            twist_clean = re.sub(r'[^\w\s]', '', twist)[:60]
            prompts.append(f"{twist_clean}, dramatic reveal, {style_suffix}")

        # ── Deduplicate while preserving order ────────────────────────────────
        seen = set()
        unique_prompts = []
        for p in prompts:
            key = p[:40]  # Compare first 40 chars
            if key not in seen:
                seen.add(key)
                unique_prompts.append(p)

        # ── Fill remaining slots with niche fallbacks ─────────────────────────
        fallback_queries = NICHE_FALLBACK_QUERIES.get(niche, [f"{topic}, {style_suffix}"])
        while len(unique_prompts) < num_scenes:
            fallback = fallback_queries[len(unique_prompts) % len(fallback_queries)]
            unique_prompts.append(f"{fallback}, {style_suffix}")

        # Trim to exact number needed
        unique_prompts = unique_prompts[:num_scenes]

        logger.info(f"Scene prompts generated ({len(unique_prompts)} for {num_scenes} scenes):")
        for i, p in enumerate(unique_prompts[:5]):  # Log first 5 only
            logger.debug(f"  Scene {i+1}: {p[:80]}...")
        if len(unique_prompts) > 5:
            logger.debug(f"  ... and {len(unique_prompts)-5} more scenes")

        return unique_prompts

    # ------------------------------------------------------------------
    # Pollinations AI image fetcher
    # ------------------------------------------------------------------
    def _fetch_pollinations_image(self, prompt: str, output_path: str,
                                   width: int = 1080, height: int = 1920,
                                   seed: int = None) -> bool:
        import urllib.parse
        try:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            _seed = seed if seed is not None else random.randint(0, 99999)
            encoded = urllib.parse.quote(prompt)
            url = (
                f"https://image.pollinations.ai/prompt/{encoded}"
                f"?width={width}&height={height}&seed={_seed}&nologo=true&enhance=true"
            )
            resp = requests.get(url, timeout=90)
            resp.raise_for_status()

            content_type = resp.headers.get("content-type", "")
            if "image" not in content_type and len(resp.content) < 10_000:
                logger.warning(f"Pollinations returned non-image: {prompt[:50]}")
                return False

            with open(output_path, "wb") as f:
                f.write(resp.content)

            size = os.path.getsize(output_path)
            if size < 5_000:
                os.remove(output_path)
                return False

            logger.success(f"Pollinations ✅ scene {output_path[-20:]} ({size//1024} KB)")
            return True
        except Exception as e:
            logger.warning(f"Pollinations fetch failed: {e}")
            return False

    def _fetch_ai_images(self, prompts: list, output_paths: list,
                          width: int = 1080, height: int = 1920) -> list:
        successful = []
        for i, (prompt, path) in enumerate(zip(prompts, output_paths)):
            seed = i * 137 + 42
            ok = self._fetch_pollinations_image(prompt, path, width, height, seed)
            if ok:
                successful.append(path)
            else:
                ok = self._fetch_pollinations_image(prompt, path, width, height, seed + 1000)
                if ok:
                    successful.append(path)
                else:
                    logger.warning(f"Scene {i+1} image failed after retry")
        return successful

    # ------------------------------------------------------------------
    # Main run method — UPGRADED with rapid cutting
    # ------------------------------------------------------------------
    def run(self, script: dict, video_id: str, output_dir: str = "/tmp",
            extracted: dict = None, *args, **kwargs) -> dict:
        niche   = self._get_niche()
        emotion = script.get("emotion", "inspiration")

        if extracted:
            script["_extracted"] = extracted

        duration   = self.video_config.get("duration_seconds", 55)

        # ── UPGRADE: Rapid cutting — 1 scene per ~3 seconds (was ~8 seconds) ──
        # For 55s video: ~18 scenes. Min 12, max 22.
        num_scenes = max(12, min(22, int(duration // 3)))

        logger.info(
            f"VisualDirectorAgent → niche={niche} emotion={emotion} "
            f"scenes={num_scenes} (rapid cut: 1 per ~3s) video={video_id}"
        )

        width  = self.image_config.get("width",  1080)
        height = self.image_config.get("height", 1920)

        use_ai_images = (niche in AI_IMAGE_NICHES)

        if use_ai_images:
            logger.info(f"Strategy: AI-generated images (Pollinations) for niche={niche}")
            return self._run_ai_images(
                script, video_id, output_dir, niche, emotion,
                num_scenes, width, height
            )
        else:
            logger.info(f"Strategy: Stock video clips (Pexels/Pixabay) for niche={niche}")
            return self._run_stock_video(
                script, video_id, output_dir, niche, emotion, num_scenes
            )

    # ------------------------------------------------------------------
    # Strategy A: AI-generated images
    # ------------------------------------------------------------------
    def _run_ai_images(self, script, video_id, output_dir,
                        niche, emotion, num_scenes, width, height) -> dict:
        scene_prompts = self._build_scene_prompts(script, niche, num_scenes)
        image_paths   = [
            f"{output_dir}/{video_id}_scene_{i:02d}.jpg"
            for i in range(len(scene_prompts))
        ]

        successful = self._fetch_ai_images(scene_prompts, image_paths, width, height)

        if len(successful) >= 4:
            logger.success(
                f"AI images: {len(successful)}/{num_scenes} fetched | "
                f"KB preset: {EMOTION_KB_PRESET.get(emotion, 'slow_zoom_in')}"
            )
            return {
                "success":        True,
                "image_paths":    successful,
                "is_video":       False,
                "source":         "pollinations_ai",
                "kb_preset":      EMOTION_KB_PRESET.get(emotion, "slow_zoom_in"),
                "scene_prompts":  scene_prompts,
                "query_used":     scene_prompts[0] if scene_prompts else "",
            }

        logger.warning("Pollinations insufficient — falling back to Pexels images")
        return self._run_pexels_images(
            script, video_id, output_dir, niche, emotion,
            num_scenes, width, height
        )

    # ------------------------------------------------------------------
    # Strategy B: Stock video clips
    # ------------------------------------------------------------------
    def _run_stock_video(self, script, video_id, output_dir,
                          niche, emotion, num_scenes) -> dict:
        topic    = script.get("topic_brief", {}).get("topic", script.get("title", ""))
        keywords = " ".join(topic.split()[:3])
        query    = f"{keywords} {emotion}".strip()[:80]

        clip_paths = [
            f"{output_dir}/{video_id}_clip_{i:02d}.mp4"
            for i in range(num_scenes)
        ]

        result = self.video_fetcher.fetch_clips(
            query=query,
            output_paths=clip_paths,
            niche=niche,
            emotion=emotion,
            min_duration=2,   # Was 4 — allow shorter clips for rapid cutting
            max_duration=8,   # Was 15 — cap at 8s to force variety
        )

        successful_clips = [
            p for p in result.get("clip_paths", [])
            if p and os.path.exists(p) and os.path.getsize(p) > 50_000
        ]

        if len(successful_clips) >= 4:
            logger.success(f"Stock video: {len(successful_clips)}/{num_scenes} clips fetched")
            return {
                "success":     True,
                "image_paths": successful_clips,
                "is_video":    True,
                "source":      "pexels_stock",
                "kb_preset":   EMOTION_KB_PRESET.get(emotion, "slow_zoom_in"),
                "query_used":  query,
            }

        logger.warning("Stock clips insufficient — falling back to Pexels still images")
        return self._run_pexels_images(
            script, video_id, output_dir, niche, emotion,
            num_scenes,
            self.image_config.get("width",  1080),
            self.image_config.get("height", 1920),
        )

    # ------------------------------------------------------------------
    # Pexels still images (universal fallback)
    # ------------------------------------------------------------------
    def _run_pexels_images(self, script, video_id, output_dir,
                            niche, emotion, num_scenes, width, height) -> dict:
        scene_prompts = self._build_scene_prompts(script, niche, num_scenes)
        image_paths   = [
            f"{output_dir}/{video_id}_pexels_{i:02d}.jpg"
            for i in range(num_scenes)
        ]

        primary_query = scene_prompts[0] if scene_prompts else f"{niche} {emotion}"

        img_result = self.image_server.call(
            "fetch_images",
            query=primary_query[:80],
            output_paths=image_paths,
            width=width,
            height=height,
        )

        fetched = [
            img["path"]
            for img in img_result.get("images", [])
            if img.get("success") and os.path.exists(img.get("path", ""))
        ]

        if fetched:
            logger.info(f"Pexels fallback: {len(fetched)} images")
            return {
                "success":     True,
                "image_paths": fetched,
                "is_video":    False,
                "source":      "pexels_images",
                "kb_preset":   EMOTION_KB_PRESET.get(emotion, "slow_zoom_in"),
                "query_used":  primary_query,
            }

        logger.error("All visual sources failed")
        return {
            "success":     False,
            "image_paths": [],
            "is_video":    False,
            "error":       "All visual sources failed",
        }
